#dev version
version: '3'
services:
  mongo:
    image: "mongo"
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_PASSWORD: ${MONGO_PASSWORD-magic2021}
      MONGO_USER: ${MONGO_USER-db_test_bot}
      MONGO_URL: ${MONGO_URL-magic_base}

  node-red:
    image: nodered/node-red
    volumes:
       - node-red-data:/data
    ports:
      - "1880:1880"
    environment:
      TZ: Europe/Moscow
      
volumes:
  node-red-data:
